# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import eleven_tts
from eleven_tts.tts.voices_api import VoicesApi  # noqa: E501
from eleven_tts.rest import ApiException


class TestVoicesApi(unittest.TestCase):
    """VoicesApi unit test stubs"""

    def setUp(self):
        self.api = VoicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_voice_v1_voices_add_post(self):
        """Test case for add_voice_v1_voices_add_post

        Add Voice  # noqa: E501
        """
        pass

    def test_delete_voice_v1_voices_voice_id_delete(self):
        """Test case for delete_voice_v1_voices_voice_id_delete

        Delete Voice  # noqa: E501
        """
        pass

    def test_edit_voice_settings_v1_voices_voice_id_settings_edit_post(self):
        """Test case for edit_voice_settings_v1_voices_voice_id_settings_edit_post

        Edit Voice Settings  # noqa: E501
        """
        pass

    def test_edit_voice_v1_voices_voice_id_edit_post(self):
        """Test case for edit_voice_v1_voices_voice_id_edit_post

        Edit Voice  # noqa: E501
        """
        pass

    def test_get_default_voice_settings_v1_voices_settings_default_get(self):
        """Test case for get_default_voice_settings_v1_voices_settings_default_get

        Get Default Voice Settings  # noqa: E501
        """
        pass

    def test_get_voice_settings_v1_voices_voice_id_settings_get(self):
        """Test case for get_voice_settings_v1_voices_voice_id_settings_get

        Get Voice Settings  # noqa: E501
        """
        pass

    def test_get_voice_v1_voices_voice_id_get(self):
        """Test case for get_voice_v1_voices_voice_id_get

        Get Voice  # noqa: E501
        """
        pass

    def test_get_voices_v1_voices_get(self):
        """Test case for get_voices_v1_voices_get

        Get Voices  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
