# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import eleven_tts
from eleven_tts.models.eleven_body_edit_voice_v1_voices_voice_id_edit_post import ElevenBodyEditVoiceV1VoicesVoiceIdEditPost  # noqa: E501
from eleven_tts.rest import ApiException


class TestElevenBodyEditVoiceV1VoicesVoiceIdEditPost(unittest.TestCase):
    """ElevenBodyEditVoiceV1VoicesVoiceIdEditPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElevenBodyEditVoiceV1VoicesVoiceIdEditPost(self):
        """Test ElevenBodyEditVoiceV1VoicesVoiceIdEditPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eleven_tts.models.eleven_body_edit_voice_v1_voices_voice_id_edit_post.ElevenBodyEditVoiceV1VoicesVoiceIdEditPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
