# coding: utf-8

"""
    ElevenLabs API Documentation

    This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://beta.elevenlabs.io. Our API is experimental so all endpoints are subject to change.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ElevenBodyDeleteHistoryItemsV1HistoryDeletePost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'history_item_ids': 'list[str]'
    }

    attribute_map = {
        'history_item_ids': 'history_item_ids'
    }

    def __init__(self, history_item_ids=None):  # noqa: E501
        """ElevenBodyDeleteHistoryItemsV1HistoryDeletePost - a model defined in Swagger"""  # noqa: E501
        self._history_item_ids = None
        self.discriminator = None
        self.history_item_ids = history_item_ids

    @property
    def history_item_ids(self):
        """Gets the history_item_ids of this ElevenBodyDeleteHistoryItemsV1HistoryDeletePost.  # noqa: E501

        A list of history items to remove, you can get IDs of history items and other metadata using the GET https://api.elevenlabs.io/v1/history endpoint.  # noqa: E501

        :return: The history_item_ids of this ElevenBodyDeleteHistoryItemsV1HistoryDeletePost.  # noqa: E501
        :rtype: list[str]
        """
        return self._history_item_ids

    @history_item_ids.setter
    def history_item_ids(self, history_item_ids):
        """Sets the history_item_ids of this ElevenBodyDeleteHistoryItemsV1HistoryDeletePost.

        A list of history items to remove, you can get IDs of history items and other metadata using the GET https://api.elevenlabs.io/v1/history endpoint.  # noqa: E501

        :param history_item_ids: The history_item_ids of this ElevenBodyDeleteHistoryItemsV1HistoryDeletePost.  # noqa: E501
        :type: list[str]
        """
        if history_item_ids is None:
            raise ValueError("Invalid value for `history_item_ids`, must not be `None`")  # noqa: E501

        self._history_item_ids = history_item_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ElevenBodyDeleteHistoryItemsV1HistoryDeletePost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ElevenBodyDeleteHistoryItemsV1HistoryDeletePost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
